version: "3"

services:
  nginx:
    container_name: web-1
    restart: always
    image: nginx:1.11.6-alpine
    ports:
      - 8081:80 # 自己的端口:docker内的端口
    volumes:
      - ./docker/conf.d:/etc/nginx/conf.d
      - .:/var/www
      - ./log:/var/log/nginx
    links:
      - php
  db:
    container_name: mysql-1
    image: mysql
    command: [
      '--default_authentication_plugin=mysql_native_password',
      '--character-set-server=utf8',
      '--collation-server=utf8_unicode_ci'
    ]
    restart: always
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: orders
  php:
    container_name: php-1
    build: ./docker
    restart: always
    links:
      - db
    volumes:
      - .:/var/www
